# Generated by Django 3.2.6 on 2021-11-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(blank=True, choices=[('bg-warning', 'RED'), ('bg-success', 'GREEN'), ('bg-danger', 'YELLOW')], max_length=50, verbose_name='Priority'),
        ),
    ]
